$(document).ready(function(){
    $("#chitiet").click(function(){
        $(".chitiet").show();
        $(".luoi").hide();
    });
    $("#luoi").click(function(){
        $(".luoi").show();
        $(".chitiet").hide();
    });
});